/**
 * Tileset Import Script
 *
 * Reads the Donarg Office Tileset PNG and extracts sprite regions based on
 * the atlas configuration, generating a TypeScript file with SpriteData constants.
 *
 * Usage:
 *   npm run import-tileset            — Generate tilesetSprites.ts
 *   npm run import-tileset -- --preview  — Also generate an HTML preview file
 */
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { PNG } from 'pngjs'
import { ATLAS_ENTRIES } from './tileset-atlas.js'

const TILE_PX = 16 // each grid cell is 16x16 pixels

const pngPath = join(__dirname, '..', 'assets', 'office-tileset.png')
const outPath = join(__dirname, '..', 'webview-ui', 'src', 'office', 'sprites', 'tilesetSprites.ts')
const previewPath = join(__dirname, '..', 'tileset-preview.html')

// ── Read PNG ────────────────────────────────────────────────────

const pngBuffer = readFileSync(pngPath)
const png = PNG.sync.read(pngBuffer)
const { width, height, data } = png

console.log(`Tileset: ${width}x${height} pixels (${width / TILE_PX}x${height / TILE_PX} tiles)`)

// ── Extract pixel data ──────────────────────────────────────────

function getPixel(x: number, y: number): { r: number; g: number; b: number; a: number } {
  const idx = (y * width + x) * 4
  return { r: data[idx], g: data[idx + 1], b: data[idx + 2], a: data[idx + 3] }
}

function toHex(r: number, g: number, b: number): string {
  return '#' + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1).toUpperCase()
}

interface ExtractedSprite {
  name: string
  label: string
  data: string[][] // SpriteData format
  category: string
  footprintW: number
  footprintH: number
  isDesk: boolean
}

const sprites: ExtractedSprite[] = []

for (const entry of ATLAS_ENTRIES) {
  const pxW = Math.round(entry.w * TILE_PX)
  const pxH = Math.round(entry.h * TILE_PX)
  const startX = Math.round(entry.col * TILE_PX)
  const startY = Math.round(entry.row * TILE_PX)

  // Bounds check
  if (startX + pxW > width || startY + pxH > height) {
    console.warn(`  WARN: ${entry.name} at (${entry.col},${entry.row}) ${entry.w}x${entry.h} exceeds tileset bounds — skipping`)
    continue
  }

  const rows: string[][] = []
  for (let y = startY; y < startY + pxH; y++) {
    const row: string[] = []
    for (let x = startX; x < startX + pxW; x++) {
      const { r, g, b, a } = getPixel(x, y)
      if (a < 128) {
        row.push('') // transparent
      } else {
        row.push(toHex(r, g, b))
      }
    }
    rows.push(row)
  }

  sprites.push({
    name: entry.name,
    label: entry.label,
    data: rows,
    category: entry.category,
    footprintW: entry.footprintW,
    footprintH: entry.footprintH,
    isDesk: entry.isDesk,
  })

  console.log(`  ${entry.name} (${pxW}x${pxH}px) from (${startX},${startY})`)
}

// ── Generate TypeScript ─────────────────────────────────────────

function spriteToTS(name: string, data: string[][]): string {
  const lines: string[] = []
  lines.push(`export const TS_${name}: SpriteData = [`)
  for (const row of data) {
    // Compress transparent runs for readability
    const cells = row.map((c) => (c === '' ? '_' : `'${c}'`))
    lines.push(`  [${cells.join(',')}],`)
  }
  lines.push(']')
  return lines.join('\n')
}

const tsLines: string[] = [
  '/**',
  ' * AUTO-GENERATED by scripts/import-tileset.ts — DO NOT EDIT',
  ` * Source: assets/office-tileset.png (Donarg Office Tileset)`,
  ` * Generated: ${new Date().toISOString()}`,
  ' */',
  "import type { SpriteData } from '../types.js'",
  '',
  "const _ = '' // transparent",
  '',
]

for (const sprite of sprites) {
  tsLines.push(`/** ${sprite.label} (${sprite.data[0].length}x${sprite.data.length}px) */`)
  tsLines.push(spriteToTS(sprite.name, sprite.data))
  tsLines.push('')
}

writeFileSync(outPath, tsLines.join('\n'))
console.log(`\nGenerated: ${outPath}`)
console.log(`  ${sprites.length} sprites extracted`)

// ── Preview HTML (optional) ─────────────────────────────────────

if (process.argv.includes('--preview')) {
  const previewItems = sprites
    .map((s) => {
      const w = s.data[0].length
      const h = s.data.length
      const scale = 3
      const canvasW = w * scale
      const canvasH = h * scale
      // Render as inline CSS pixel art
      const pixels: string[] = []
      for (let y = 0; y < h; y++) {
        for (let x = 0; x < w; x++) {
          const c = s.data[y][x]
          if (c !== '') {
            pixels.push(
              `<div style="position:absolute;left:${x * scale}px;top:${y * scale}px;width:${scale}px;height:${scale}px;background:${c}"></div>`,
            )
          }
        }
      }
      return `
      <div style="display:inline-block;margin:8px;text-align:center;vertical-align:top">
        <div style="position:relative;width:${canvasW}px;height:${canvasH}px;background:#222;border:1px solid #555;image-rendering:pixelated">
          ${pixels.join('')}
        </div>
        <div style="font-size:10px;color:#aaa;margin-top:2px">${s.name}</div>
        <div style="font-size:9px;color:#666">${w}x${h} | ${s.footprintW}x${s.footprintH} | ${s.category}${s.isDesk ? ' [desk]' : ''}</div>
      </div>`
    })
    .join('\n')

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Tileset Preview</title>
<style>body{background:#1a1a2e;color:#eee;font-family:monospace;padding:16px}</style>
</head><body>
<h2>Donarg Office Tileset — Extracted Sprites (${sprites.length})</h2>
<p>Each sprite shown at 3x scale. Grid below shows the footprint and category.</p>
${previewItems}
</body></html>`

  writeFileSync(previewPath, html)
  console.log(`Preview: ${previewPath}`)
}
